import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
    <head>
      <title>Emojeezer</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    </head>
      <body>
        {children}
        <footer className={"w-full ml-20 mb-10"}>
          Made by choucroute melba
          <div className={"flex flex-col *:text-gray-500"}>
            <a href={"/"}><pre>Home</pre></a>
            <a href={"https://github.com/choucroute/emojeezer"}><pre>Github</pre></a>
            { process.env.ENV_TYPE === "dev" &&
                <a href={"/uninstallation/feedback?version=168.1.1.1&buildtype=debug"}><pre>Uninstallation feedback</pre></a>}

          </div>
        </footer>
      </body>
    </html>
  );
}
