import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {children}
        <footer>
          Made by choucroute melba
          <div className={"flex flex-col"}>
            <a href={"https://github.com/choucroute/emojeezer"}>Github</a>
            <a href={"/uninstallation/feedback?version=168.1.1.1&buildtype=debug"}>Uninstallation feedback</a>
            <a href={"/"}>Home</a>
          </div>
        </footer>
      </body>
    </html>
  );
}
